version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  # Optionally, you might want to add a database service
  # Here's an example with PostgreSQL:
  db:
    image: postgres:15-alpine
    container_name: go-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sendpulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nextjs:
    image: denoland/deno:alpine
    container_name: sendpulse-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git &&
             git clone https://github.com/donnaloia/nextjs-shadcn-starter . &&
             deno task dev
    environment:
      - NODE_ENV=development
    volumes:
      - nextjs_data:/app  # Persist data between container restarts
    restart: unless-stopped

volumes:
  postgres_data:
  nextjs_data: